version: "3.6"

services:
  api:
    hostname: api
    container_name: "api"
    build:
      context: .
    ports:
      - 8889:8889

    restart: unless-stopped
    command: bash -c "uvicorn src.main:app --host 0.0.0.0  --port 8889 --reload --log-level debug"
networks:
  cvat-server:
    external: true
